### ISSUE TITLE
Update RBAC for documented Service Account 

### ISSUE THREAD

**Issue by Samze** [vmware-tanzu/tanzu-application-platform-reference-service-packages#12]
Today the ServiceAccount we recommend to use for kapp installations has overly permissive RBAC. See [here](https://github.com/vmware-tanzu/tanzu-application-platform-reference-packages/blob/main/amazon/ack/rds/sa.yaml)
```
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudsql-install
  namespace: default
rules:
- apiGroups: ["*"] # TODO: use more fine-grained RBAC permissions
  resources: ["*"]
  verbs: ["*"]
```

We should narrow the scope to just the resources managed by the kapp deployment.
